fix: exclude cicd tests from unit tests

diff --git a/cicd/cloudbuild_dev_and_sandbox.yaml b/cicd/cloudbuild_dev_and_sandbox.yaml
--- a/cicd/cloudbuild_dev_and_sandbox.yaml
+++ b/cicd/cloudbuild_dev_and_sandbox.yaml
@@ -4,6 +4,9 @@ steps:
       - '-c'
       - |
         set -e
+
+        echo === Verify tooling ===
+
         gcloud --version
         make --version
         pip --version
@@ -16,16 +19,20 @@ steps:
         export SA_EMAIL=$_BACKEND_SA_EMAIL
         export VERIFY_API_URL=$_VERIFY_API_URL
 
+        echo === Install dependencies and run unit tests ===
+
         poetry install
 
-        #make load-design-system-templates
+        make load-design-system-templates
 
         export UI_SA_ID_TOKEN=$(gcloud auth print-identity-token --impersonate-service-account=$_UI_SA_EMAIL)
-        poetry run pytest --cov=utils --cov=survey_assist_ui --cov-report=term-missing --cov-fail-under=75 | tee coverage-report.txt
-        #if grep -q "FAIL Required test coverage" coverage-report.txt; then
-        #  echo "ERROR: Target coverage was not reached, stopping pipeline."
-        #  exit 1
-        #fi
+        poetry run pytest --ignore=cicd --cov=utils --cov=survey_assist_ui --cov-report=term-missing --cov-fail-under=75 | tee coverage-report.txt
+        if grep -q "FAIL Required test coverage" coverage-report.txt; then
+          echo "ERROR: Target coverage was not reached, stopping pipeline."
+          exit 1
+        fi
+
+        echo === Build, tag and push image ===
 
         poetry version -s > /workspace/version.txt
 
@@ -35,7 +42,16 @@ steps:
         docker push $_GAR_IMAGE:latest
         docker push $_GAR_IMAGE:$SHORT_SHA
 
+        echo === Deploy survey UI ===
+
         gcloud run deploy survey-ui --image=$_GAR_IMAGE:$SHORT_SHA --region $LOCATION --project $_TARGET_PROJECT_ID
+
+        echo === Run smoke tests ===
+
+        #export SURVEY_ASSIST_UI_URL=$(gcloud parametermanager parameters versions describe $1 --parameter=infra-test-config --location=global --project ons-cicd-surveyassist --format=json | python3 -c "import sys, json; print(json.load(sys.stdin)['payload']['data'])" | base64 --decode | python3 -c "import sys, json; print(json.load(sys.stdin)['alb-survey-url'])")
+        export SURVEY_ASSIST_UI_URL="https://proxy-api-670504361336.europe-west2.run.app"
+        export SA_ID_TOKEN=$(gcloud auth print-identity-token --impersonate-service-account=$_UI_SA)
+        pytest cicd
     id: Unit Test, Build, Tag and Deploy UI
     entrypoint: bash
 timeout: 600s
